<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../CulinaryBlog.Application/CulinaryBlog.Application.csproj" />
    <ProjectReference Include="../CulinaryBlog.Domain/CulinaryBlog.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Bogus" />
  </ItemGroup>
</Project>

