// <auto-generated />
// LƯU Ý: file này được VIẾT TAY (thay cho `dotnet ef migrations add`, công cụ chưa cài
// được trong môi trường phát triển hiện tại) để đóng vai trò metadata mô tả model cho
// migration InitialCreate. Nếu sau này cài được dotnet-ef, nên xoá cả thư mục Migrations
// và chạy lại `dotnet ef migrations add InitialCreate` để EF tự sinh bản chính thức,
// đảm bảo khớp tuyệt đối với model runtime (DbContext + Configurations không cần sửa).
using System;
using CulinaryBlog.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CulinaryBlog.Infrastructure.Migrations
{
    [DbContext(typeof(CulinaryBlogDbContext))]
    [Migration("20260922103000_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
            {
                b.Property<string>("Id").HasMaxLength(450).HasColumnType("character varying(450)");
                b.Property<string>("ConcurrencyStamp").IsConcurrencyToken().HasColumnType("text");
                b.Property<string>("Name").HasMaxLength(256).HasColumnType("character varying(256)");
                b.Property<string>("NormalizedName").HasMaxLength(256).HasColumnType("character varying(256)");

                b.HasKey("Id");
                b.HasIndex("NormalizedName").IsUnique().HasDatabaseName("RoleNameIndex");
                b.ToTable("AspNetRoles", (string)null);

                b.HasData(
                    new
                    {
                        Id = "20000000-0000-0000-0000-000000000001",
                        ConcurrencyStamp = "b9f6e7d1-0000-0000-0000-000000000001",
                        Name = "Admin",
                        NormalizedName = "ADMIN"
                    },
                    new
                    {
                        Id = "20000000-0000-0000-0000-000000000002",
                        ConcurrencyStamp = "b9f6e7d1-0000-0000-0000-000000000002",
                        Name = "Author",
                        NormalizedName = "AUTHOR"
                    });
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                b.Property<string>("ClaimType").HasColumnType("text");
                b.Property<string>("ClaimValue").HasColumnType("text");
                b.Property<string>("RoleId").IsRequired().HasMaxLength(450).HasColumnType("character varying(450)");

                b.HasKey("Id");
                b.HasIndex("RoleId");
                b.ToTable("AspNetRoleClaims", (string)null);
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                b.Property<string>("ClaimType").HasColumnType("text");
                b.Property<string>("ClaimValue").HasColumnType("text");
                b.Property<string>("UserId").IsRequired().HasMaxLength(450).HasColumnType("character varying(450)");

                b.HasKey("Id");
                b.HasIndex("UserId");
                b.ToTable("AspNetUserClaims", (string)null);
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
            {
                b.Property<string>("LoginProvider").HasMaxLength(128).HasColumnType("character varying(128)");
                b.Property<string>("ProviderKey").HasMaxLength(128).HasColumnType("character varying(128)");
                b.Property<string>("ProviderDisplayName").HasColumnType("text");
                b.Property<string>("UserId").IsRequired().HasMaxLength(450).HasColumnType("character varying(450)");

                b.HasKey("LoginProvider", "ProviderKey");
                b.HasIndex("UserId");
                b.ToTable("AspNetUserLogins", (string)null);
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
            {
                b.Property<string>("UserId").HasMaxLength(450).HasColumnType("character varying(450)");
                b.Property<string>("RoleId").HasMaxLength(450).HasColumnType("character varying(450)");

                b.HasKey("UserId", "RoleId");
                b.HasIndex("RoleId");
                b.ToTable("AspNetUserRoles", (string)null);
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
            {
                b.Property<string>("UserId").HasMaxLength(450).HasColumnType("character varying(450)");
                b.Property<string>("LoginProvider").HasMaxLength(128).HasColumnType("character varying(128)");
                b.Property<string>("Name").HasMaxLength(128).HasColumnType("character varying(128)");
                b.Property<string>("Value").HasColumnType("text");

                b.HasKey("UserId", "LoginProvider", "Name");
                b.ToTable("AspNetUserTokens", (string)null);
            });

            modelBuilder.Entity("CulinaryBlog.Domain.Entities.ApplicationUser", b =>
            {
                b.Property<string>("Id").HasMaxLength(450).HasColumnType("character varying(450)");
                b.Property<int>("AccessFailedCount").HasColumnType("integer");
                b.Property<string>("AvatarUrl").HasMaxLength(500).HasColumnType("character varying(500)");
                b.Property<string>("Bio").HasColumnType("text");
                b.Property<string>("ConcurrencyStamp").IsConcurrencyToken().HasColumnType("text");
                b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone").HasDefaultValueSql("now()");
                b.Property<string>("DisplayName").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
                b.Property<string>("Email").HasMaxLength(256).HasColumnType("character varying(256)");
                b.Property<bool>("EmailConfirmed").HasColumnType("boolean");
                b.Property<bool>("IsActive").HasColumnType("boolean").HasDefaultValue(true);
                b.Property<bool>("LockoutEnabled").HasColumnType("boolean");
                b.Property<DateTimeOffset?>("LockoutEnd").HasColumnType("timestamp with time zone");
                b.Property<string>("NormalizedEmail").HasMaxLength(256).HasColumnType("character varying(256)");
                b.Property<string>("NormalizedUserName").HasMaxLength(256).HasColumnType("character varying(256)");
                b.Property<string>("PasswordHash").HasColumnType("text");
                b.Property<string>("PhoneNumber").HasColumnType("text");
                b.Property<bool>("PhoneNumberConfirmed").HasColumnType("boolean");
                b.Property<string>("SecurityStamp").HasColumnType("text");
                b.Property<bool>("TwoFactorEnabled").HasColumnType("boolean");
                b.Property<string>("UserName").HasMaxLength(256).HasColumnType("character varying(256)");

                b.HasKey("Id");
                b.HasIndex("IsActive");
                b.HasIndex("NormalizedEmail").HasDatabaseName("EmailIndex");
                b.HasIndex("NormalizedUserName").IsUnique().HasDatabaseName("UserNameIndex");
                b.ToTable("AspNetUsers", (string)null);
            });

            modelBuilder.Entity("CulinaryBlog.Domain.Entities.RefreshToken", b =>
            {
                b.Property<Guid>("Id").HasColumnType("uuid");
                b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<string>("CreatedByIp").HasMaxLength(45).HasColumnType("character varying(45)");
                b.Property<DateTimeOffset>("ExpiresAt").HasColumnType("timestamp with time zone");
                b.Property<Guid>("FamilyId").HasColumnType("uuid");
                b.Property<string>("ReplacedByTokenHash").HasMaxLength(64).IsFixedLength().HasColumnType("character(64)");
                b.Property<DateTimeOffset?>("RevokedAt").HasColumnType("timestamp with time zone");
                b.Property<string>("RevokedByIp").HasMaxLength(45).HasColumnType("character varying(45)");
                b.Property<string>("RevocationReason").HasMaxLength(100).HasColumnType("character varying(100)");
                b.Property<string>("TokenHash").IsRequired().HasMaxLength(64).IsFixedLength().HasColumnType("character(64)");
                b.Property<string>("UserId").IsRequired().HasMaxLength(450).HasColumnType("character varying(450)");

                b.HasKey("Id");
                b.HasIndex("FamilyId");
                b.HasIndex("TokenHash").IsUnique();
                b.HasIndex("UserId");
                b.HasIndex("UserId", "RevokedAt");
                b.ToTable("RefreshTokens", (string)null);
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
            {
                b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                    .WithMany().HasForeignKey("RoleId").OnDelete(DeleteBehavior.Cascade).IsRequired();
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
            {
                b.HasOne("CulinaryBlog.Domain.Entities.ApplicationUser", null)
                    .WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
            {
                b.HasOne("CulinaryBlog.Domain.Entities.ApplicationUser", null)
                    .WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
            {
                b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                    .WithMany().HasForeignKey("RoleId").OnDelete(DeleteBehavior.Cascade).IsRequired();

                b.HasOne("CulinaryBlog.Domain.Entities.ApplicationUser", null)
                    .WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
            {
                b.HasOne("CulinaryBlog.Domain.Entities.ApplicationUser", null)
                    .WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
            });

            modelBuilder.Entity("CulinaryBlog.Domain.Entities.RefreshToken", b =>
            {
                b.HasOne("CulinaryBlog.Domain.Entities.ApplicationUser", "User")
                    .WithMany("RefreshTokens").HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();

                b.Navigation("User");
            });

            modelBuilder.Entity("CulinaryBlog.Domain.Entities.ApplicationUser", b =>
            {
                b.Navigation("RefreshTokens");
            });
#pragma warning restore 612, 618
        }
    }
}
