// <auto-generated />
using System;
using CulinaryBlog.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CulinaryBlog.Infrastructure.Migrations
{
    [DbContext(typeof(CulinaryBlogDbContext))]
    partial class CulinaryBlogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CulinaryBlog.Domain.Entities.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<int>("CookTimeMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<string>("Instructions")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("PrepTimeMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamptz");

                    b.Property<int>("Servings")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("IDX_Recipe_AuthorId");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("IDX_Recipe_Slug")
                        .HasFilter("\"IsDeleted\" = false");

                    b.HasIndex("CategoryId", "Status")
                        .HasDatabaseName("IDX_Recipe_Category_Status")
                        .HasFilter("\"IsDeleted\" = false");

                    b.HasIndex("Status", "PublishedAt")
                        .HasDatabaseName("IDX_Recipe_Status_PublishedAt")
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("Recipes", (string)null);
                });

            modelBuilder.Entity("CulinaryBlog.Domain.Entities.RecipeSlugHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("OldSlug")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("OldSlug")
                        .HasDatabaseName("IDX_RecipeSlugHistory_OldSlug");

                    b.HasIndex("RecipeId")
                        .HasDatabaseName("IDX_RecipeSlugHistory_RecipeId");

                    b.ToTable("RecipeSlugHistories", (string)null);
                });

            modelBuilder.Entity("CulinaryBlog.Domain.Entities.Recipe", b =>
                {
                    b.OwnsOne("CulinaryBlog.Domain.ValueObjects.RecipeNutrition", "Nutrition", b1 =>
                        {
                            b1.Property<Guid>("RecipeId")
                                .HasColumnType("uuid");

                            b1.Property<decimal?>("Calories")
                                .HasPrecision(8, 2)
                                .HasColumnType("numeric(8,2)")
                                .HasColumnName("Nutrition_Calories");

                            b1.Property<decimal?>("Carbohydrates")
                                .HasPrecision(8, 2)
                                .HasColumnType("numeric(8,2)")
                                .HasColumnName("Nutrition_Carbohydrates");

                            b1.Property<decimal?>("Fat")
                                .HasPrecision(8, 2)
                                .HasColumnType("numeric(8,2)")
                                .HasColumnName("Nutrition_Fat");

                            b1.Property<decimal?>("Fiber")
                                .HasPrecision(8, 2)
                                .HasColumnType("numeric(8,2)")
                                .HasColumnName("Nutrition_Fiber");

                            b1.Property<decimal?>("Protein")
                                .HasPrecision(8, 2)
                                .HasColumnType("numeric(8,2)")
                                .HasColumnName("Nutrition_Protein");

                            b1.Property<decimal?>("Sodium")
                                .HasPrecision(8, 2)
                                .HasColumnType("numeric(8,2)")
                                .HasColumnName("Nutrition_Sodium");

                            b1.Property<string>("Source")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasDefaultValue("Manual")
                                .HasColumnName("Nutrition_Source");

                            b1.HasKey("RecipeId");

                            b1.ToTable("Recipes");

                            b1.WithOwner()
                                .HasForeignKey("RecipeId");
                        });

                    b.Navigation("Nutrition");
                });
#pragma warning restore 612, 618
        }
    }
}
